# Generated by Django 5.2.2 on 2025-06-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_create_roles_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "descripcionc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "permisos",
            },
        ),
    ]
