# Generated by Django 5.2.2 on 2025-06-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_permiso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol_Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.permiso"
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.rol"
                    ),
                ),
            ],
            options={
                "db_table": "rol_permisos",
                "unique_together": {("rol", "permiso")},
            },
        ),
        migrations.AddField(
            model_name="rol",
            name="permisos",
            field=models.ManyToManyField(
                related_name="roles", through="app1.Rol_Permiso", to="app1.permiso"
            ),
        ),
    ]
